### ISSUE TITLE
Vert.x 3.3.1 umbrella

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#132]
tracks the 3.3.1 issues - edit this list when needed:
- [x] https://github.com/eclipse/vert.x/issues/1480 : PR https://github.com/eclipse/vert.x/pull/1493, https://github.com/vert-x3/vertx-dropwizard-metrics/pull/38
- [x] https://github.com/eclipse/vert.x/issues/1479 : PR https://github.com/eclipse/vert.x/pull/1488
- [x] https://github.com/eclipse/vert.x/issues/1489 : Alex going to look at it
- [x] https://github.com/eclipse/vert.x/issues/1491 : PR https://github.com/eclipse/vert.x/pull/1492
- [x] https://github.com/eclipse/vert.x/issues/1494 : PR https://github.com/eclipse/vert.x/pull/1495 
- [x] https://github.com/eclipse/vert.x/issues/1496
- [x] https://github.com/vert-x3/vertx-web/pull/295
- [x] https://github.com/vert-x3/vertx-codegen/issues/85 : PR https://github.com/vert-x3/vertx-codegen/pull/87
- [x] https://github.com/vert-x3/vertx-jdbc-client/pull/66
- [x] https://github.com/vert-x3/vertx-redis-client/pull/62
- [x] https://github.com/vert-x3/vertx-stomp/issues/20 - PR: https://github.com/vert-x3/vertx-stomp/pull/21
- [x] https://github.com/vert-x3/vertx-web/pull/406
- [x] https://github.com/vert-x3/vertx-web/pull/407
- [x] https://github.com/vert-x3/vertx-hawkular-metrics/issues/40 - PR: https://github.com/vert-x3/vertx-hawkular-metrics/pull/41
- [x] https://github.com/vert-x3/vertx-web/pull/410 (restore jQuery post behavior)

Documentation fixes:
- [x] https://github.com/vert-x3/vertx-rx/pull/44
- [x] https://github.com/vert-x3/vertx-web-site/pull/157
- [x] https://github.com/eclipse/vert.x/issues/1320 - PR: https://github.com/eclipse/vert.x/pull/1490
- [x] https://github.com/vert-x3/vertx-web-site/pull/159
- [x] https://github.com/vert-x3/vertx-web-site/issues/160 - PR: https://github.com/eclipse/vert.x/pull/1501
- [x] Documentation update commits for https://github.com/vert-x3/vertx-amqp-bridge since 3.3.0

**Comment by vietj** [comment]
yay!

**Comment by pmlopes** [comment]
last minute update, we need to restore the jQuery behavior since it would be to disruptive to be standard compliant.

**Comment by vietj** [comment]
👍

**Comment by cescoffier** [comment]
@davsclaus has made a small update in the camel bridge too (bump camel version). I think it has been merged before the last staging (let me check)

**Comment by cescoffier** [comment]
Nope it didn't made the cut.

**Comment by vietj** [comment]
that raises a problem.

the code that has been staged does not reflect anymore what is in vertx-camel-bridge master.

so either we have to restage because of this new commits or we have to make a “git push —force” to vertx-camel-bridge to remove these changes.

**Comment by cescoffier** [comment]
I can simply revert the PR, so the binary would be the same.
I'm not a big fan of rewriting the history.

**Comment by vietj** [comment]
I'm not either, let's revert and I'll rebase locally my clone on the extra commits
