### ISSUE TITLE
Vert.x 3.3.2 umbrella

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#135]
This is an _umbrella_ issue tracking the progress of the Vert.x 3.3.2 release.
It's a bug fix release only !
- [X] - https://github.com/vert-x3/vertx-unit/pull/34
- [x] - https://github.com/vert-x3/vertx-dropwizard-metrics/issues/39
- [x] - https://github.com/vert-x3/vertx-dropwizard-metrics/issues/41
- [x] - https://github.com/eclipse/vert.x/issues/1504
- [X] - https://github.com/vert-x3/vertx-camel-bridge/issues/15

**Comment by cescoffier** [comment]
Version released !
