### ISSUE TITLE
Vert.x 3.3.3 umbrella

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#136]
This is an _umbrella_ issue tracking the progress of the Vert.x 3.3.3 release. Bug fix only.
- vertx-core
  - [x] - [Using random port with HttpServer only works for first server](https://github.com/eclipse/vert.x/issues/1596)
  - [x] - [Proxying - Host header not formed properly](https://github.com/eclipse/vert.x/issues/1511)
  - [x] - [ns.upgradeToSsl fails hostname cert check](https://github.com/eclipse/vert.x/issues/1512)
  - [x] - [UnsupportedOperationException with unlocatable hosts config file](https://github.com/eclipse/vert.x/issues/1517)
  - [x] - [Load the ndots value on linux from /etc/resolv.conf and allow a value of 0](https://github.com/eclipse/vert.x/issues/1525)
  - [x] - [Implement HTTP Proxy for non SSL HttpClient](https://github.com/eclipse/vert.x/issues/1498)
  - [x] - [Fix message producer](https://github.com/eclipse/vert.x/pull/1513)
  - [x] - [DatagramSocket should use unpooled buffers](https://github.com/eclipse/vert.x/issues/1554)
  - [x] - [Remove openssl keycert format limitations](https://github.com/eclipse/vert.x/pull/1565)
  - [X] - [localhost resolve issue in Windows when using netty resolver](https://github.com/eclipse/vert.x/issues/1524)
  - [x] - [Multivalued server cookies should be seen as a single semi colon separated header](https://github.com/eclipse/vert.x/pull/1566)
  - [x] - [CompositeFuture join method](https://github.com/eclipse/vert.x/pull/1555)
  - [x] - [netty resolver may get ipv6 addresses even when only ipv4 is available](https://github.com/eclipse/vert.x/issues/1570)
  - [x] - [Blocked thread warning when opening or closing an AsyncFile](https://github.com/eclipse/vert.x/issues/1573)
  - [x] - [Close the shared worker pools when closing Vertx](https://github.com/eclipse/vert.x/issues/1577)
  - [x] - [Rethrow the RejectedExecutionException when a worker task is rejected](https://github.com/eclipse/vert.x/issues/1578)
  - [ ] - [Log a warn when the Connection header is used in HTTP/2 response headers](https://github.com/eclipse/vert.x/issues/1580)
  - [X] - https://github.com/vert-x3/issues/issues/156
  - [X] - [Deprecate and @GenIgnore CompositeFuture#result(int) in favor of CompositeFuture#resultAt(int)](https://github.com/eclipse/vert.x/issues/1605)
  - [x] - https://github.com/eclipse/vert.x/pull/1585
  - [x] - https://github.com/eclipse/vert.x/pull/1593
  - [X] - [NetClient with SOCKS Proxy checks wrong hostname on upgradeToSsl()](https://github.com/eclipse/vert.x/issues/1602)
- vertx-jdbc-client
  - [X] - [SQLConnection context must remain the same than the context obtaining the SQLConnection](https://github.com/vert-x3/vertx-jdbc-client/issues/68)
  - [X] - [Shared JDBCClient deadlock](https://github.com/vert-x3/vertx-jdbc-client/issues/69)
- vertx-shell
  - [X] - [non-interactive SSH run](https://github.com/vert-x3/vertx-shell/pull/27)
  - [X] - [Use the correct event loop on authentication callback](https://github.com/vert-x3/vertx-shell/issues/26)
  - [X] - [Upgrade to termd 1.1.1](https://github.com/vert-x3/vertx-shell/issues/28)
  - [X] - [verticle-deploy with options](https://github.com/vert-x3/vertx-shell/issues/17)
- vertx-dropwizard-metrics
  - [x] - [http client endpoint metric are not under basename vert.x](https://github.com/vert-x3/vertx-dropwizard-metrics/issues/43)
  - [X] - https://github.com/vert-x3/vertx-dropwizard-metrics/issues/37
  - [X] - https://github.com/vert-x3/issues/issues/178
- vertx-lang-groovy
  - [X] - [Upgrade Groovy to 2.4.7](https://github.com/vert-x3/vertx-lang-groovy/issues/37)
  - [x] - [Cached primitive always return the default primitive value and don't call the delegate](https://github.com/vert-x3/vertx-lang-groovy/issues/36)
  - [x] - [groovy RoutingContext.statusCode() always return 0](https://github.com/vert-x3/vertx-web/issues/437)
- vertx-auth
  - [x] - [OAuth getToken don't response when java.net.UnknownHostException is thrown](https://github.com/vert-x3/vertx-auth/issues/81)
- vertx-web
  - [x] - https://github.com/vert-x3/vertx-web/pull/408
  - [x] - https://github.com/vert-x3/vertx-web/pull/421
  - [x] - https://github.com/vert-x3/vertx-web/pull/441
  - [x] - https://github.com/vert-x3/vertx-web/issues/414
- vertx-service-discovery
  - [X] - https://github.com/vert-x3/vertx-service-discovery/issues/34
  - [X] - https://github.com/vert-x3/vertx-service-discovery/issues/33
  - [X] - https://github.com/vert-x3/vertx-service-discovery/issues/28
  - [X]  - https://github.com/vert-x3/vertx-service-discovery/issues/40
  - [X]  - https://github.com/vert-x3/vertx-service-discovery/issues/39
  - [X] - https://github.com/vert-x3/vertx-service-discovery/pull/31
  - [X] - https://github.com/vert-x3/vertx-service-discovery/pull/29
  - [X] - https://github.com/vert-x3/vertx-service-discovery/issues/37
- vertx-stomp
  - [X] - https://github.com/vert-x3/vertx-stomp/issues/22
- vertx-amqp-bridge
  - [X] - https://github.com/vert-x3/vertx-amqp-bridge/issues/10
  - [X] - https://github.com/vert-x3/vertx-amqp-bridge/issues/11
- vertx-proton
  - [X] - https://github.com/vert-x3/vertx-proton/issues/28
  - [X] - https://github.com/vert-x3/vertx-proton/issues/29
  - [X] - https://github.com/vert-x3/vertx-proton/issues/30
  - [X] - https://github.com/vert-x3/vertx-proton/issues/31
  - [X] - https://github.com/vert-x3/vertx-proton/pull/32
- vert-codegen
  - [X] - [Method overloaded by subclass is absent in its method list](https://github.com/vert-x3/vertx-codegen/issues/102)
  - [X] - [Inherited method that changes the generic type should be part of the class model](https://github.com/vert-x3/vertx-codegen/issues/101)
- unsorted
  - [ ] - https://github.com/vert-x3/vertx-jgroups/issues/26
  - [X] - [Update to jruby 9.1.5.0](https://github.com/vert-x3/vertx-lang-ruby/issues/20)
  - [X] - [Update to RxJava 1.1.9](https://github.com/vert-x3/vertx-rx/issues/52)

**Comment by luengnat** [comment]
https://github.com/vert-x3/vertx-auth/issues/81 seems to be resolved already.

**Comment by pmlopes** [comment]
Closing since 3.3.3 is already released.

**Comment by cescoffier** [comment]
Issue marked as invalid just to avoid collecting it in the release notes.
