### ISSUE TITLE
Vert.x 3.4.1 umbrella

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#240]
This is an umbrella issue tracking the progress of the Vert.x 3.4.1 release.
It's a bug fix release only !

- [x] - [Vert.x 3.4.0 doesn't start with Netty 4.1.9.Final](https://github.com/eclipse/vert.x/issues/1872)
- [x] - [Handle HTTP/1.1 decode errors](https://github.com/eclipse/vert.x/issues/1862)
- [x] - [Web session can't be clustered in 3.4.0](https://github.com/vert-x3/vertx-web/issues/542)
- [x] - [Vertx Groovy compiler transformation throws NPE when using a closure with no parameters](https://github.com/vert-x3/vertx-lang-groovy/issues/46)
- [x] - [WorkerExecutor callback should run on caller context](https://github.com/eclipse/vert.x/issues/1864)
- [x] - [HeaderParser uses a max line size value that is too small ](https://github.com/vert-x3/vertx-web/issues/548)
- [x] - [Upgrade to Infinispan 9.0.0.CR3](https://github.com/vert-x3/vertx-infinispan/issues/22)
- [x] - [Update io.reactivex:rxjava version to 1.2.7](https://github.com/vert-x3/vertx-rx/issues/80)
- [x] - [Connecting to bad AMQ socket causes Out Of Memory](https://github.com/vert-x3/vertx-amqp-bridge/issues/14)
- [x] - [update to proton-j 0.18.0](https://github.com/vert-x3/vertx-proton/issues/43)
- [x] - [WorkerExecutor must order tasks on the current Context and not on itself](https://github.com/eclipse/vert.x/pull/1869)
- [x] - [Vert.x RxJava - Adapt to WorkerExecutor changes](https://github.com/vert-x3/vertx-rx/issues/83)
- [x] - [Vert.x Ignite - Adapt to WorkerExecutor changes](https://github.com/vert-x3/vertx-ignite/issues/40)
- [x] - [Vert.x Hazelcast - Adapt to WorkerExecutor changes](https://github.com/vert-x3/vertx-hazelcast/issues/62)
- [x] - [Vert.x Infinispan - Adapt to WorkerExecutor changes](https://github.com/vert-x3/vertx-infinispan/issues/23)
- [x] - [Use the per-connection explicit task queue as this is what we want](https://github.com/vert-x3/vertx-jdbc-client/pull/91)
- [x] - [Fix missing GAV-coordinates in adoc for scala-modules](https://github.com/vert-x3/vertx-lang-scala/pull/28)
- [x] - [Fix broken links into ScalaDoc in adoc for scala-modules](https://github.com/vert-x3/vertx-lang-scala/pull/28)
- [x] - [Fix documentation of the yaml support](https://github.com/vert-x3/vertx-config/issues/6)
- [x] - The release notes contain _invalid_ issues
- [x] - [MQTT server exposes the connection status of remote client through the endpoint](https://github.com/vert-x3/vertx-mqtt-server/commit/ba9f920efdbd1fe3e9a8007cd2c0024369623e3c)
- [x] - [MQTT server handles client-id "zero-bytes" (as MQTT spec 3.1.1)](https://github.com/vert-x3/vertx-mqtt-server/pull/14)
- [x] - [Kafka client provides new offsets (and timestamp) get methods based on new Kafka 0.10.1.1](https://github.com/vert-x3/vertx-kafka-client/pull/18)
- [x] - [In case of NO_HANDLERS, vertx handler executed in wrong context and thread type](https://github.com/eclipse/vert.x/issues/1870)
- [x] - [Incorrect producer back pressure when send fails](https://github.com/vert-x3/vertx-kafka-client/issues/24)
- [x] - [KafkaWriteStreamImpl.java uses a blocking function ](https://github.com/vert-x3/vertx-kafka-client/issues/21)
- [x] - [Shared KafkaProducer should only shared the Producer and not the KafkaWriteStream](https://github.com/vert-x3/vertx-kafka-client/issues/23)
- [x] - [Use embeddable kotlin compiler](https://github.com/vert-x3/vertx-lang-kotlin/issues/11)
- [x] - [Do not assume country is provided in accept-language](https://github.com/vert-x3/vertx-web/pull/551)

**Comment by alexlehm** [comment]
added the HeaderParser issue (why don't have issues a changelog?)

**Comment by ppatierno** [comment]
@vietj my MQTT additions are two new features (not bug fixes). Is it ok for you ?
Furthermore, the second one (client-id zero bytes) breaks the API regarding the endpointHandler method because I need an Handle<AsyncResult<MqttEndpoint>> there instead of a Handler<MqttEndpoint>. Need to handle a scenario when the endpoint can't be created due to protocol spec.

**Comment by vietj** [comment]
small features ?

**Comment by vietj** [comment]
ok to change, it's tech preview

**Comment by vietj** [comment]
make sure the examples are not broken in vertx-examples repo

**Comment by ppatierno** [comment]
@vietj I see that examples refer to 3.4.0 version for now, so nothing is broken. I'll change them when we decide to switch from examples with 3.4.0 to 3.4.1.

**Comment by cescoffier** [comment]
Does it mean the changes you made breaks the examples ? (if I run the current set of examples using 3.4.1, does it work ?)

**Comment by vietj** [comment]
@cescoffier I think indeed there is a change from Handler<T> -> Handler<AsyncResult<T>> in mqtt exmaples

**Comment by mhstnsc** [comment]
Hi guys, a 3.4.1 release would be much appreciated given some serious bugs so do you think is necessary  to wait for the examples or "The release notes contain invalid issues"

**Comment by cescoffier** [comment]
@mhstnsc don't worry, the release process has already been started. The last issue is fixed in //.
