### ISSUE TITLE
Vert.x 3.5.2 umbrella issue

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#352]
List of back-ported bugs

- vertx-stack
   - [x] Jackson 2.9.5 upgrade 
- vertx-core
  - [x] [Missing VertxGen annotation on JsonEventType](https://github.com/eclipse/vert.x/issues/2412)
  - [ ] [Native transport SO_REUSEPORT should be set on server bootstrap as option instead of child option](https://github.com/eclipse/vert.x/issues/2413)
  - [x] [Typo prevents configuration of EpollTransport](https://github.com/eclipse/vert.x/issues/2379)
  - [x] [Json#decodeValue cannot deserialize a JSON null/number/boolean from a Buffer](https://github.com/eclipse/vert.x/issues/2361)
  - [x] [HTTP server connection keeps processing pending pipelined requests when connection close](https://github.com/eclipse/vert.x/issues/2365)
  - [x] [HttpClient pool gets inconsistent on a synchronous connection failure](https://github.com/eclipse/vert.x/issues/2370)
  - [x] [Report HTTP client pool internal failures as connect errors](https://github.com/eclipse/vert.x/issues/2414)
  - [x] [Don't route connection write promise failures in the pipeline](https://github.com/eclipse/vert.x/issues/2373)
  - [x] [Http1xOrH2CHandler should remove itself before firing the buffer](https://github.com/eclipse/vert.x/issues/2375)
  - [x] [HTTP client keep alive timeout](https://github.com/eclipse/vert.x/issues/2326)
  - [x] [The http server request exception handler should observe the response as closed on a close event](https://github.com/eclipse/vert.x/issues/2377)
  - [x] [HTTP/2 via HTTP/1.1 connection upgrade does not respect the protocol](https://github.com/eclipse/vert.x/issues/2362)
  - [x] [The HTTP server should always resume the request when the last chunk is processed](https://github.com/eclipse/vert.x/issues/2380)
  - [x] [HttpClient pool should use a LIFO policy instead of a FIFO policy](https://github.com/eclipse/vert.x/issues/2415)
  - [x] [HTTP client requests should always prefix request URI with / for absolute queries](https://github.com/eclipse/vert.x/issues/2416)
  - [x] [App Id in the start command doc is wrong](https://github.com/eclipse/vert.x/issues/2341)
  - [x] [Remove HttpClientImpl#close method synchronization](https://github.com/eclipse/vert.x/issues/1358)
  - [x] [Improve connection exception logging](https://github.com/eclipse/vert.x/issues/2437)
  - [x] [Incorrect VertxHttp2Stream checkNextTick implementation](https://github.com/eclipse/vert.x/issues/2457)
  - [x] [WebSocket end handler should be called immediately to signal stream ended](https://github.com/eclipse/vert.x/issues/2461)
  - [x] [WorkExecutorImpls are not removed from closeHooks when they are closed](https://github.com/eclipse/vert.x/issues/2464)
  - [x] [Http header CR / LF validation](https://github.com/eclipse/vert.x/issues/2470)
  - [x] [FileSystem readDir does not list all entries when resolving from Classpath](https://github.com/eclipse/vert.x/issues/2126)
- vertx-mqtt
  - [x] [Use NetSocket as lock on MqttClientConnection instead of itself](https://github.com/vert-x3/vertx-mqtt/issues/93)
  - [x] [Windows redeploy does not provide valid inline verticle configuration](https://github.com/eclipse/vert.x/issues/2480)
- vertx-lang-scala
  - [x] [ClassCastException when using eventbus sockjs bridge](https://github.com/vert-x3/vertx-lang-scala/issues/65)
  - [x] [Possible regression on JsonObject in version 3.5.1](https://github.com/vert-x3/vertx-lang-scala/issues/66)
- vertx-web
   - [x] [RountingContext#getBodyAsJsonXXX create unnecessary intermediate String](https://github.com/vert-x3/vertx-web/pull/835)
  - [x] [Avoid NPE on empty path requests](https://github.com/vert-x3/vertx-web/pull/909)
  - [x] [Fix behaviour of cookies on error](https://github.com/vert-x3/vertx-web/pull/880)
  - [x] [Don't retain a ref to HttpClientResponse in HttpResponse](https://github.com/vert-x3/vertx-web/issues/923)
  - [x] [Don't keep a reference in the HTTP pool connection listener to the connection waiter](https://github.com/eclipse/vert.x/issues/2477)
- vertx-web-api-contract
  - [x] [Fixed #874 Invalid JsonArray body](https://github.com/vert-x3/vertx-web/pull/887)
  - [x] [Resolve refs for requestBody definitions](https://github.com/vert-x3/vertx-web/pull/886)
  - [x] [Allow setting customised BodyHandler](https://github.com/vert-x3/vertx-web/pull/869) 
  - [x] [Add global handlers to be added to router before swagger routes](https://github.com/vert-x3/vertx-web/pull/877) 
  - [x] [Regexes fixes](https://github.com/vert-x3/vertx-web/pull/884) with [semicolon fix](https://github.com/vert-x3/vertx-web/pull/940)
  - [x] [Fix #850](https://github.com/vert-x3/vertx-web/pull/885)
  - [x] [Fix #939](https://github.com/vert-x3/vertx-web/pull/941)
- vertx-mysql-postgresql-client
   - [x] [query/queryStream/update handlers invoked again if they throw an exception](https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/104)
- vertx-auth
  - [x] [Wrong Log level fix](https://github.com/vert-x3/vertx-auth/pull/186)
  - [x] [Explicitly specify we prefer JSON](https://github.com/vert-x3/vertx-auth/pull/200)
  - [x] [Fix Shiro context](https://github.com/vert-x3/vertx-auth/pull/205)
  - [x] [Add GDPR docs](https://github.com/vert-x3/vertx-auth/pull/184)
  - [x] [Fix Instagram default config](https://github.com/vert-x3/vertx-auth/pull/192)
  - [x] [Fix documentation regarding shiro LDAP properties](https://github.com/vert-x3/vertx-auth/pull/196)
- vertx-micrometer-metrics
  - [x] [Fix OOM #27: do not store metrics for faster access](https://github.com/vert-x3/vertx-micrometer-metrics/pull/28)
- vertx-codegen
  - [x] [Expose the referenced enums to the template](https://github.com/vert-x3/vertx-codegen/pull/160)
- vertx-proton
  - [x] [codegen dependency should not be compile scoped](https://github.com/vert-x3/vertx-proton/issues/68)
- vertx-amqp-bridge
  - [x] [do not include codegen in the final artifact list](https://github.com/vert-x3/vertx-amqp-bridge/pull/16)
- vertx-sync
  - [x] [Rework of the test cases for awaitResult and timeouts](https://github.com/vert-x3/vertx-sync/pull/25)
- vertx-rx
  - [x] [ContextScheduler tasks are still referenced in the worker actions map after execution](https://github.com/vert-x3/vertx-rx/issues/136)
- vertx-circuit-breaker
  - [x] [Change org.hdrhistogram:HdrHistogram:jar version to 2.1.10](https://github.com/vert-x3/vertx-circuit-breaker/issues/27)
- vertx-junit5
  - [x] Updated to JUnit 5.2.0
  - [x] Fix the documentation on how to fail using a user-managed test context

Edit and append to the list...

**Comment by codepitbull** [comment]
https://github.com/vert-x3/vertx-lang-scala/issues/65
https://github.com/vert-x3/vertx-lang-scala/issues/66

**Comment by Kusig** [comment]
Is there any timeframe known for 3.5.2? We got in really deep troubles with 3.5.1 due to the huge known performance problem (TCP Connection Close of the http client) and are currently stuck.  Cherry picking didn't work as there are too much dependencies encountered even to other vert.x modules. Therefore we would be really interested in any information about this.

**Comment by vietj** [comment]
there is now a 3.5 branch in vertx-core you can try @Kusig it's also deployed as snapshot in sonatype oss repository.

we aim to release soon.

**Comment by testn** [comment]
Does it have netty dependency upgrade?

**Comment by vietj** [comment]
no because we can't upgrade grpc version and that would conflict.

perhaps we can test it with latest netty and if it works well (testsuite) then tell people to override the version.
