### ISSUE TITLE
Remove MVEL from code generation

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#367]
Umbrella issue for the following tasks:

- [x] [Provide an MVEL agnostic generator](https://github.com/vert-x3/vertx-codegen/issues/176)
- [x] [Move the data object converter generator to codegen](https://github.com/eclipse/vert.x/issues/2436)
- [x] [Rewrite the data object converter generator without MVEL](https://github.com/vert-x3/vertx-codegen/issues/177)
- [x] [Rewrite the cheatsheet converter generator without MVEL](https://github.com/vert-x3/vertx-codegen/issues/178)
- [x] [Rewrite vertx-rx generator without MVEL](https://github.com/vert-x3/vertx-rx/pull/149)
- [x] [Rewrite vertx-lang-kotlin generator without MVEL](https://github.com/vert-x3/vertx-lang-kotlin/pull/58)
- [x] [Rewrite vertx-service-proxy generator without MVEL](https://github.com/vert-x3/vertx-service-proxy/issues/71)
- [x] [Rewrite vertx-lang-scala generator without MVEL](https://github.com/vert-x3/vertx-lang-scala/issues/72)
- [ ] rewrite vertx-lang-groovy generator without MVEL
- [x] Rewrite vertx-lang-js generator without MVEL
- [x] Rewrite vertx-lang-ceylon generator without MVEL
- [ ] Rewrite vertx-lang-ruby generator without MVEL
