### ISSUE TITLE
Vert.x 3.5.3 umbrella issue

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#384]
List of back-ported bugs:

- vertx-core
  - [x] [HttpClient must use the http scheme for non SSL connections](https://github.com/eclipse/vert.x/issues/2533)
  - [x] [HttpClient idle state handler should be added first when the connection is borrowed from the pool](https://github.com/eclipse/vert.x/issues/2532)
  - [x] [HttpServer does not clean the channel pipeline after HTTP/1 upgrade to H2C](https://github.com/eclipse/vert.x/issues/2519)
  - [x] [Disable HttpClient TCP idle timeout when connection is in the pool](https://github.com/eclipse/vert.x/issues/2517)
  - [x] [HttpClient should behave according to the HTTP version returned by the server and not sent by the client](https://github.com/eclipse/vert.x/issues/2514)
  - [x] [Internal references to local Locks taken using SharedData.getLock() are not cleaned up](https://github.com/eclipse/vert.x/issues/2484#issuecomment-398786614)
  - [x] [Websocket client and server don't send back close frame in closing handshake](https://github.com/eclipse/vert.x/issues/2486)
  - [x] [NetServer bootstrap should set SO_LINGER option on the child channel instead of the server channel](https://github.com/eclipse/vert.x/issues/2498#issuecomment-398663142)
  - [x] [FutureImpl shall release the handler after completion](https://github.com/eclipse/vert.x/issues/2490)
- vertx-sql-common
  - [x] [SQLOperations single methods should declare a nullable asynchronous result](https://github.com/vert-x3/vertx-sql-common/issues/62)
- vertx-web
  - [x] [CSRF validation is incomplete](https://github.com/vert-x3/vertx-web/issues/970)
- vertx-web-api-contract
  - [x] [Fixed bad global security handlers mounting](https://github.com/vert-x3/vertx-web/issues/936)
- vertx-auth
  - [x] [OAuth2AuthHandler not failing for invalid JWT](https://github.com/vert-x3/vertx-auth/issues/216)
- vertx-proton
  - [x] [misuse of the proton-j transport input](https://github.com/vert-x3/vertx-proton/issues/72)
  - [x] [expose missing free() method on links and sessions](https://github.com/vert-x3/vertx-proton/issues/82)
- vertx-lang-kotlin
  - [x] [Fix to allow instants and byte[] to be used via kotlin extension](https://github.com/vert-x3/vertx-lang-kotlin/pull/60)
  - [x] [Back-port documentation overrides](https://github.com/vert-x3/vertx-lang-kotlin/issues/62)
- vertx-mqtt
  - [x] [Improve MqttClient synchronization](https://github.com/vert-x3/vertx-mqtt/issues/104)
  - [x] [Race condition in server when accepting a connection](https://github.com/vert-x3/vertx-mqtt/issues/94)
