### ISSUE TITLE
Vert.x 3.5.4 umbrella issue

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#401]
List of back-ported bugs:

- vertx-core
  - [x] [HttpClient connection should be resumed when response ends](https://github.com/eclipse/vert.x/issues/2593)
  - [x] [Improve the ALPN detection to work on latest JDK 11](https://github.com/eclipse/vert.x/issues/2625)
  - [x] [Fix FileResolver for OSGi bundle resources](https://github.com/eclipse/vert.x/pull/2549)
  - [x] [NullPointerException when reporting a deployment failure without a completion handler](https://github.com/eclipse/vert.x/issues/2590)
  - [x] [HTTP/2 settings update can miss acknowledgement](https://github.com/eclipse/vert.x/issues/2609)
  - [x] [WebSocket client does not report server protocol violations on the WebSocket exception handler](https://github.com/eclipse/vert.x/issues/2610)
  - [x] [Incorrect javadoc for MessageProducer#send](https://github.com/eclipse/vert.x/issues/2618)
  - [x] [FileResolver fails when path contains `+` character](https://github.com/eclipse-vertx/vert.x/issues/2619)
  - [x] [Extra chunk for request with no content.](https://github.com/eclipse-vertx/vert.x/issues/2607)
  - [x] [VertxHttpHeaders#add(CharSequence,CharSequence) does not used AsciiString cached hashcode value](https://github.com/eclipse-vertx/vert.x/issues/2446)
  - [x] [HttpServerResponse content headers improvements](https://github.com/eclipse-vertx/vert.x/issues/2630)
  - [x] [RecordParser: Limit the record size](https://github.com/eclipse-vertx/vert.x/pull/2635)
  - [x] [WebSocket upgrade request body limit](https://github.com/eclipse-vertx/vert.x/issues/2648)
- vertx-config
   - [x] [Spring Config Server: wrong overriding order](https://github.com/vert-x3/vertx-config/issues/54)
- vertx-jdbc-client
  - [x] [Avoid to signal the connection close to the metrics when the connection is already closed](https://github.com/vert-x3/vertx-jdbc-client/issues/139)
- vertx-micrometer-metrics
   - [x] [Increment responseCount counter](https://github.com/vert-x3/vertx-micrometer-metrics/pull/43)
- vertx-stack
  - [x] [Jackson upgrade to 2.9.6](https://github.com/vert-x3/issues/issues/403)
- vertx-auth
  - [x] [OAuth2AuthHandler does not introspect a parsed token](https://github.com/vert-x3/vertx-auth/issues/241)
- vertx-hazelcast
  - [x] [ Cluster manager is corrupted after merging of hazelcast partition](https://github.com/vert-x3/vertx-hazelcast/issues/90)
- vertx-web
  - [x] [Fix a potential deadlock case in failure handling](https://github.com/vert-x3/vertx-web/issues/930)
  - [x] [Fix a potential XXE when loading validation XML schemas](https://github.com/vert-x3/vertx-web/issues/1021)
  - [x] [Neutralize property backward slashes sequences in StaticHandler](https://github.com/vert-x3/vertx-web/issues/1025)

**Comment by kerko** [comment]
It would be great if we could backport this fix: https://github.com/vert-x3/vertx-micrometer-metrics/pull/43

**Comment by vietj** [comment]
it makes sense to me, @jotak can you take care of this ?

**Comment by luengnat** [comment]
any plan to update netty/grpc?

**Comment by vietj** [comment]
unfortunately, not in 3.5.4, 3.6.0 will be released within a few weeks from now.
