### ISSUE TITLE
Vert.x 3.6.1

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#428]
Umbrella issue, add here the issues that will fix in 3.6.1
Estimated release date 17/12/18

- vertx-codegen
  - [x] [vertx-codegen OSGI module can't be resolved in Apache Felix](https://github.com/vert-x3/vertx-codegen/pull/225)
- vertx-core
  - [x] [Deprecate the HttpClient request/response methods that use an Handler](https://github.com/eclipse-vertx/vert.x/pull/2744)
  - [x] [HttpClientRequest should be reset on a timeout](https://github.com/eclipse-vertx/vert.x/issues/2745)
  - [x] [NetSocket StartTLS upgrade failure should report an exception to the socket exception handler](https://github.com/eclipse-vertx/vert.x/issues/2748)
  - [x] [Improper parsing of multiple search domains in resolv.conf](https://github.com/eclipse-vertx/vert.x/issues/2752)
  - [x] [JsonObject cannot map to class with Instant or byte array field](https://github.com/eclipse-vertx/vert.x/issues/2753)
- vertx-tcp-eventbus-bridge
  - [x] [vertx-tcp-eventbus-bridge is missing generated code](https://github.com/vert-x3/issues/issues/430)
- vertx-rx
  - [x] [RxJava2: missing adpaters for async result handlers](https://github.com/vert-x3/vertx-rx/issues/170)
  - [x] [Unnamed module reads package io.vertx.reactivex from both vertx.rx.java2 and vertx.rx.java2.gen](https://github.com/vert-x3/issues/issues/431)
  - [x] [Expose WriteStream as Observer](https://github.com/vert-x3/vertx-rx/issues/115)
  - [x] [rx-gen module can't be used in OSGI environment crashing rx-java2 bundle](https://github.com/vert-x3/vertx-rx/issues/172)
- vertx-dropwizard-metrics
  - [ ] [Write additional response metrics for configured server urls](https://github.com/vert-x3/vertx-dropwizard-metrics/pull/80)
  - [x] [Cannot configure baseName from file](https://github.com/vert-x3/vertx-dropwizard-metrics/issues/71)
- vertx-web
  - [x] [SockJS session should always receive messages on context event loop](https://github.com/vert-x3/vertx-web/issues/1112)
  - [x] [change sockjs library url](https://github.com/vert-x3/vertx-web/pull/1098)
  - [x] [WebClient body stream codec should complete the stream for async files when it completes asynchronously](https://github.com/vert-x3/vertx-web/issues/1101)
  - [x] [staticHandler with range header produces bad response](https://github.com/vert-x3/vertx-web/issues/1027)
  - [x] [Web Client header removed during redirect after 3.6.0 upgrade](https://github.com/vert-x3/vertx-web/issues/1096)
- vertx-web-api-contract
  - [x] https://github.com/vert-x3/vertx-web/issues/1099
  - [x] [Regressions from 3.5.x](https://github.com/vert-x3/vertx-web/pull/1104)
  - [x] [Optional body in request body definition throws 404](https://github.com/vert-x3/vertx-web/issues/1105)
- vertx-junit5
  - [x] [Fix numberOfPasses int overflow](https://github.com/vert-x3/vertx-junit5/pull/48)
- vertx-mysq-postgresql-client
  - [x] [Allow empty transactions](https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/132)
- vertx-lang-groovy
  - [x] [Update to Groovy 2.5.4](https://github.com/vert-x3/vertx-lang-groovy/pull/67)
  - [x] [Remove usage of groovy-all](https://github.com/vert-x3/vertx-lang-groovy/issues/68)
- vertx-stack
  - [x] [Missing SQL client in API docs](https://github.com/vert-x3/vertx-sql-common/issues/65)
- vertx-cassandra-client
  - [x] [Disconnect leads to NPE when no callback is provided](https://github.com/vert-x3/vertx-cassandra-client/issues/14)
  - [x] [ListenableFuture adapter does not invoke handler](https://github.com/vert-x3/vertx-cassandra-client/issues/15)
- vertx-zookeeper
  - [x] [KeeperErrorCode = NoNode issue after upgrading to 3.6.0](https://github.com/vert-x3/vertx-zookeeper/issues/73)
