### ISSUE TITLE
Vertx 3.6.3

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#435]
This is the umbrella issue for 3.6.3

- vertx-core
  - [x] [HTTP2 request/response exception handler should not be called when response is ended](https://github.com/eclipse-vertx/vert.x/issues/2803)
  - [x] [Document that executeBlocking should not be used for long blocking operations](https://github.com/eclipse-vertx/vert.x/issues/2801)
  - [x] [Jackson 2.9.8 upgrade](https://github.com/vert-x3/issues/issues/442)
  - [x] [JsonParser should not resume or pause the source wrapped read stream when it is ended](https://github.com/eclipse-vertx/vert.x/issues/2790)
  - [x] [HttpServer handles incorrectly pipelined server response with sendFile](https://github.com/eclipse-vertx/vert.x/issues/2795)
  - [x] [HttpServer closes the connection prematurely when sending a large file with HTTP/1.1 without keep-alive ](https://github.com/eclipse-vertx/vert.x/issues/2794)
  - [x] [HttpClient pool improvement](https://github.com/eclipse-vertx/vert.x/issues/2787)
  - [x] [HttpClient race condition when getting a connection from the pool being closed](https://github.com/eclipse-vertx/vert.x/issues/2773)
  - [x] [HttpServer should send a valid HTTP response when no request handler and a WebSocket handler is set](https://github.com/eclipse-vertx/vert.x/issues/2785)
  - [x] [ServerWebSocket upgrade does not always fail correctly during an handshake failure](https://github.com/eclipse-vertx/vert.x/issues/2786)
  - [x] [Remove documentation for public logging API](https://github.com/eclipse-vertx/vert.x/issues/2776)
  - [x] [MessageConsumer delivers more items than requested in fetch mode](https://github.com/eclipse-vertx/vert.x/issues/2813)

- vertx-web
  - [x] [Add a JSON stream body codec](https://github.com/vert-x3/vertx-web/pull/1154)
  - [x] [Reorganized Router error handling](https://github.com/vert-x3/vertx-web/pull/1142)
  - [x] [Subsequent SockJS xhr/xhr_send causes IllegalStateException](https://github.com/vert-x3/vertx-web/issues/1135)
  - [x] [Basic access and bearer token authentication mechanisms](https://github.com/vert-x3/vertx-web/pull/1141)

- vertx-rx
  - [x] [Vert.x higher when 3.6.0 (3.6.1 and 3.6.2) is not generate reactivex service](https://github.com/vert-x3/issues/issues/440)

- vertx-cassandra-client
  - [x] [Timeout when undeploying verticle](https://github.com/vert-x3/vertx-cassandra-client/issues/17)
  - [x] [NoHostAvailableException during cassandraClient.connect leads to failure in Future.fail()](https://github.com/vert-x3/vertx-cassandra-client/issues/21)

- vertx-mongo
  - [x] [Nullable async results](https://github.com/vert-x3/issues/issues/435)

- vertx-tcp-eventbus-bridge
  - [x] [Removed `ext` from groupPackage](https://github.com/vert-x3/vertx-tcp-eventbus-bridge/pull/47)

- vertx-auth
  - [x] [Reduce logging levels in OAuth2 code](https://github.com/vert-x3/vertx-auth/issues/253)

- vertx-lang-kotlin
  - [x] [Prefer dataObjectOf functions instead of the DataObject ones](https://github.com/vert-x3/vertx-lang-kotlin/issues/103)
  - [x] [deployVerticleAwait does not have all method overloads](https://github.com/vert-x3/vertx-lang-kotlin/issues/104)

**Comment by karianna** [comment]
https://github.com/vert-x3/vertx-mongo-client/pull/170 ready to land

**Comment by vietj** [comment]
@karianna I think we should keep the PR for 3.7 instead as this will break rxjava2 generated API by replacing `Single` by `Maybe`, WDYT?

**Comment by vietj** [comment]
I'll add it in the breaking changes for RX2 for 3.6.3
