### ISSUE TITLE
Vert.x stack futurisation

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#472]
This issue keeps track of the futurisation of the Vert.x stack, it's an umbrella issue

- milestone1
   - [x] [vertx-core](https://github.com/eclipse-vertx/vert.x/issues/2998)
- milestone2
   - [x] [vertx-redis-client](https://github.com/vert-x3/vertx-redis-client/pull/165)
   - [x] [vertx-auth](https://github.com/vert-x3/vertx-auth/pull/284)
   - [x] [vertx-web](https://github.com/vert-x3/vertx-web/pull/1346)
   - [x] [vertx-bridge-common](https://github.com/vert-x3/vertx-bridge-common/pull/4)
   - [x] [vertx-mqtt](https://github.com/vert-x3/vertx-mqtt/issues/145)
   - [x] [vertx-kakfa-client](https://github.com/vert-x3/vertx-kafka-client/issues/146)
   - [x] [vertx-cassandra-client](https://github.com/vert-x3/vertx-cassandra-client/issues/36)
   - [x] [vertx-amqp-client](https://github.com/vert-x3/vertx-amqp-client/issues/22)
- milestone3
  - [x] [vertx-circuit-breaker](https://github.com/vert-x3/vertx-circuit-breaker/issues/37)
  - [x] [vertx-service-discovery](https://github.com/vert-x3/vertx-service-discovery/issues/115)
  - [x] [vertx-config](https://github.com/vert-x3/vertx-config/issues/97)
- milestone4
  - [x] [vertx-mongo-client](https://github.com/vert-x3/vertx-mongo-client/issues/205)
  - [x] [vertx-stomp](https://github.com/vert-x3/vertx-stomp/issues/60)
  - [x] [vertx-rabbitmq-client](https://github.com/vert-x3/vertx-rabbitmq-client/issues/87)
  - [x] [vertx-shell](https://github.com/vert-x3/vertx-shell/issues/41)
  - [x] vertx-health-check
  - [x] [vertx-mail-client](https://github.com/vert-x3/vertx-mail-client/pull/114)
  - [x] vertx-sql-client
  - [x] [vertx-consul-client](https://github.com/vert-x3/vertx-consul-client/issues/66)

**Comment by cvgaviao** [comment]
in which moment of futurisation plan will the Future interface extend CompletionStage?

**Comment by vietj** [comment]
Hi,

I think that's something we can think about.

At the moment I would rather keep Vert.x Future as is and add a toCompletionStage method on it rather than extending it.

Julien

**Comment by tsegismont** [comment]
@vietj how about adding the `toCompletionStage` method in milestone4 ?

**Comment by vietj** [comment]
I would like actually to come up with several proposals for Future
