### ISSUE TITLE
Vert.x 4.0 umbrella issue

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#500]
High level issue for tracking Vert.x 4 issues

### 4.0

* [x] Future API improvements
* [x] gRPC compiler rewrite using Salesforce compiler
* [x] Redis web session store
* [x] SQL Client auth
* [x] HTTP client rework
* [x] Move the MVEL codegen template to vertx-lang-ruby
* [x] Service proxy future removal
* [x] Prune verticle deployment metrics
* [x] Clustering
  * [x] SPI redesign
  * [x] ISPN 11 upgrade
  * [x] HZ 4 upgrade
  * [x] Default networking address configuration
  * [x] Vert.x 3 / 4 conflict detection
* [x] Event-bus back-pressure pruning
  * [x] message producer not anymore a write stream
* [x] Generic client metrics
  * [x] client metrics SPI
  * [x] Dropwizard client metrics
  * [x] Micrometer client metrics https://github.com/vert-x3/vertx-micrometer-metrics/issues/106
  * [x] SQL client metrics
* [x] Stack context promise
  * [x] Cassandra Client https://github.com/vert-x3/vertx-cassandra-client/pull/46
  * [x] Web GraphQL https://github.com/vert-x3/vertx-web/commit/19b6410240d86f71edc7b2613a84d38cdc39993d
  * [x] Mongo Client https://github.com/vert-x3/vertx-mongo-client/pull/219
  * [x] Redis Client
  * [x] JDBC Client https://github.com/vert-x3/vertx-jdbc-client/pull/178
  * [x] Service Config https://github.com/vert-x3/vertx-config/pull/107
  * [x] Kakfa Client
  * [x] RabbitMQ Client https://github.com/vert-x3/vertx-rabbitmq-client/issues/102
* [x] Remaining JSON improvements
  * [x] Store buffers as `Buffer` internally in addition of `byte[]` https://github.com/eclipse-vertx/vert.x/pull/3342
  * [x] codegen also respects the same codec as core (RFC7493) - https://github.com/vert-x3/vertx-codegen/pull/313
* [x] Open questions
  * [x] Log4J 1 pruning
  * [x] Vert.x Service Factory
  * [x] Maven Service Factory
  * [x] HTTP Service Factory
* [x] Classloading simplifications
  * [x] Verticle factory / `IsolatingClassLoader`
* [x] SQL templates https://github.com/eclipse-vertx/vertx-sql-client/pull/538
* [x] [Auth multi tenant support](https://github.com/vert-x3/vertx-web/commit/6665774d824775e35ef8ce2d4919298a182950f7) (web level)
* [x] OAuth2/OIDC PKCE
* [x] Webauthn
* [x] Modularity
  * [x] Automatic module names https://github.com/vert-x3/issues/issues/524
  * [x] Check split packages
* [x] JDBC SQL client https://github.com/vert-x3/vertx-jdbc-client/pull/180
* [x] SQL client back-end tracing https://github.com/eclipse-vertx/vertx-sql-client/pull/625
* [x] Healthcheck upgrade
* [x] codegen
  * [x] Data object JSON generated converter case formatting
  * [x] `@Mapper` annotation or property files? 
  * [x] `DataObjectTypeInfo` in `ClassTypeInfo`
* [x] [Prune duplicated bridge options](https://github.com/vert-x3/vertx-web/issues/1499) 
* [x] Vertx JUnit5 must depend only on core (blocking) https://github.com/vert-x3/vertx-junit5/issues/73 
* [x] Web Validation & OpenAPI
  * [x] JSON Schema
  * [x] Web Validation
  * [x] OpenAPI new module
  * [x] Web Service refactor + https://github.com/vert-x3/vertx-web/pull/1453
* [x] Web site
* [x] Convert docs to use futures
  * [x] SQL client
  * [x] Mongo client
  * [x] JUnit 5 support
  * [x] Redis Client
  * [x] Vert.x Web
  * [x] Shell
  * [x] Service Proxy
  * [x] Stomp Client
  * [x] Service Healthchecks
  * [x] Auth
* [x] Groovy doc rework https://github.com/vert-x3/vertx-lang-groovy/pull/109/files
* [x] Kotlin doc rework and generate deprecated suspending methods https://github.com/vert-x3/vertx-lang-kotlin/pull/175
* [x] Migration guide
* [x] Vert.x examples
  * [x] Use futures
  * [x] Remove code generation
* [x] Kotlin coroutine generated functions should be deprecated
* [x] [Unsatisfied checkpoints diagnosis in vertx-junit5](https://github.com/vert-x3/vertx-junit5/pull/72)
* [x] [Deprecated the `vertx-sync` Quasar-based APIs](https://github.com/vert-x3/vertx-sync/pull/40)
* [x] Vertx-Web [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) handler (backport from yoke + modernize)* * [x] Auth
  * [x] webauthn implements [MDS](https://github.com/vert-x3/vertx-auth/issues/415)

**Comment by jponge** [comment]
🥳  🎈
