### ISSUE TITLE
Vert.x 4 Roadmap

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#566]
### Other stuff

* [ ] Migrate vertx-auth to FDN

### 4.x, x > 3

* [ ] Java concurrency review
* [ ] Web Template engines cache behavior is inconsistent across engines
* [ ] Vert.x examples
  * [x] Use futures
  * [x] Move large examples to how-tos
  * [ ] Remove usage of CLI
  * [ ] Remove or replace deprecated examples (jdbc-client, old redis client, etc...)
  * [ ] Build passes without deprecation warning (for Vert.x code) for 3.9 examples
* [ ] Vert.x "K8S-Native" cluster manager (no data grid embedded)
* [ ] etc...
* [ ] Discuss backport RESTStore from yoke https://github.com/pmlopes/yoke/tree/develop/middleware/reststore
* [ ] Future/Promise lock-free implementation
* [ ] Migrate examples / How-tos to Java 17 with new language features
* [ ] auth:
  * [ ] [Oauth2 implement rfc8693](https://github.com/vert-x3/vertx-auth/issues/498)
  * [ ] [Oauth2 add support for UMA 2.0 flow](https://github.com/vert-x3/vertx-auth/issues/497)
* [ ] gRPC load balancing and name resolving SPI integration
* [ ] pool enhancements
* [ ] Client telemetry
  * [ ] Redis tracing
  * [ ] Redis metrics
* [ ] Web:
  * [ ] #594

### 4.4

* [ ] SQL Clients
  * [x] Exception reporting improvements [#1275](https://github.com/eclipse-vertx/vertx-sql-client/pull/1275)
  * [ ] Support cursor / streaming API in Oracle Client
* [x] [Enable TLS 1.3 by default](https://github.com/eclipse-vertx/vert.x/issues/4557)
* [x] [Disable TLS 1.0 and 1.1 by default](https://github.com/eclipse-vertx/vert.x/issues/4560)
* [x] Experimental io_uring support
* [x] [Mongo Driver upgrade](https://github.com/vert-x3/vertx-mongo-client/issues/289)
* [x] GraphQL
  * [x] [Instrumentation for data fetchers returning `Future`](https://github.com/vert-x3/vertx-web/issues/2329)
  * [x] [Instrumentation for data fetchers returning `JsonObject`](https://github.com/vert-x3/vertx-web/issues/2353)
  * [x] [Instrumentation for data fetchers returning `Single` and `Maybe`](https://github.com/vert-x3/vertx-rx/pull/288)
  * [x] [GraphiQL upgrade, supporting subscriptions with GraphQLWS transport](https://github.com/vert-x3/vertx-web/pull/2346)
  * [x] [Support Apollo's Automatic Persisted Queries](https://github.com/vert-x3/vertx-web/pull/1844)
* [x] Kotlin
  * [x] [Upgrade to Kotlin 1.7](https://github.com/vert-x3/vertx-lang-kotlin/issues/225)
  * [x] [ Upgrade to Kotlin Coroutines 1.6](https://github.com/vert-x3/vertx-lang-kotlin/issues/226)

#### Committed

* [x] [MySQL pipelining support](https://github.com/eclipse-vertx/vertx-sql-client/pull/1168)
* [x] [Upgrade Kafka Client to Kafka 3.x](https://github.com/vert-x3/vertx-kafka-client/pull/208)
* [x] [Vert.x Junit 5 to Eclipse Foundation](https://github.com/vert-x3/vertx-junit5/issues/108)
* [x] [Extra HTTP compression algorithms](https://github.com/eclipse-vertx/vert.x/pull/4262)
* [x] Event-bus
   * [x] Define the semantic for local vs clustered same address consumers and possibly provide greater control over the selection by the message sender see https://github.com/eclipse-vertx/vert.x/issues/4116 and https://github.com/eclipse-vertx/vert.x/issues/4000
   * [x] More flexible type based message codec selection
* [x] [Vert.x gRPC](https://github.com/eclipse-vertx/vertx-grpc)
* [x] SQL Server support Cursor
* [x] Auth:
  * [x] [User object should have a subject() read-only getter](https://github.com/vert-x3/vertx-auth/issues/464)
* [x] [URI Template RFC6570 Vert.x implementation](https://github.com/eclipse-vertx/vertx-uri-template/)
* [x] Web:
  * [x] [WebClient uri templates](https://github.com/vert-x3/vertx-web/pull/2097)
  * [x] #587
  * [x] #592
* [x] jsonschema - [update to 2020.12](https://github.com/eclipse-vertx/vertx-json-schema/issues/56)
* [x] [Service Proxy Interceptors more secure](https://github.com/vert-x3/vertx-service-proxy/issues/126)
* [x] [Service Proxy Interceptors - split authn/authz](https://github.com/vert-x3/vertx-service-proxy/issues/127)
* [x] avoid `jackson-dataformat-*` as it forces pulling `jackson-databind` dependency when the use of the library is purely internal 

#### Best effort

* [ ] Pcap logging
* [ ] [Provide opinionated REST respond-with programming style](https://github.com/vert-x3/vertx-web/pull/2089)
* [x] [Route metadata](https://github.com/vert-x3/vertx-web/issues/1963)
* [ ] Auth:
  * [ ] [Improve OIDC/OAuth2 Flow discovery](https://github.com/vert-x3/vertx-auth/issues/501)
* [ ] IO_URING tech preview
* [ ] Loom investigations
  * [x] Vert.x Core hooks for contexts 
  * [x] Future integration
  * [ ] Synchronous API
  * [ ] Stream integration

### Expected

* [x] Reference counted client (shared) (pools, etc...)
  * [x] SQL Client
  * [x] [HTTP Client](https://github.com/eclipse-vertx/vert.x/pull/4079)
* [x] [Run jUnit5 on context](https://github.com/vert-x3/vertx-junit5/issues/100)
* [x] JDK 17 Support
* [x] [MQTT 5 server support](https://github.com/vert-x3/vertx-mqtt/issues/205)
* [x] Oracle client
* [x] [SQL Server support](https://github.com/orgs/eclipse-vertx/projects/2)
  * [x] TLS support
  * [x] Azure support (`ROUTING`)
* [x] Client telemetry
  * [x] [Cassandra tracing](https://github.com/vert-x3/vertx-cassandra-client/issues/74)
* [x] [webauthn upgrade MDS2 to MDS3](https://github.com/vert-x3/vertx-auth/issues/485)
* [x] GraphQL
  * [x] [Context management with GraphQLContext object](https://github.com/vert-x3/vertx-web/issues/2023)
  * [x] [GraphQL over Websocket protocol ](https://github.com/vert-x3/vertx-web/issues/1959)
* [x] WebClient enhancements
  * [x] [Caching Web Client](https://github.com/vert-x3/vertx-web/pull/1932)
  * [x] [Add oAuth2 to WebClient](https://github.com/vert-x3/vertx-web/issues/1999)
* [x] Service Proxy / OpenAPI dispatcher security
  * [x] [OpenAPI eventbus operations should include the access_token in the message header](https://github.com/vert-x3/vertx-web/issues/1995)
* [x] [JWTAuth thread safety issues](https://github.com/vert-x3/vertx-auth/issues/502)
* [x] [MFA Authentication Handler for vert.x web](https://github.com/vert-x3/vertx-web/issues/2012)
* [x] [Correctly handle cookies](https://github.com/eclipse-vertx/vert.x/issues/3916)
* [x] [Correctly handle file cache resolving](https://github.com/eclipse-vertx/vert.x/pull/4099)
* [x] [Correclty handle Base64 regardless of the vertx core encoding](https://github.com/vert-x3/vertx-auth/issues/510)

## Others

* [ ] More metrics
* [ ] More tracing
* [ ] Stack context promise
  * [ ] Web
  * [ ] Web Client
  * [ ] Circuit Breaker
  * [ ] Auth
  * [ ] Service Discovery
  * [ ] MQTT
  * [ ] AMQP Client
  * [ ] Stomp
  * [ ] Mail Client
  * [ ] Consul Client
  * [ ] Camel Bridge
  * [ ] Metrics
  * [ ] Shell

**Comment by angelsanzn** [comment]
Could you provide a bit more info about the scope of the Oracle client item?

**Comment by vietj** [comment]
we are planning this for 4.2

**Comment by angelsanzn** [comment]
Hi Julien, thanks for the prompt reply. My question was about the scope of the feature. Is it a full Oracle DB client which does not use JDBC?

**Comment by vietj** [comment]
this is actually a wrapper of Oracle JDBC Reactive Extensions
(https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/jdbc-reactive-extensions.html#GUID-1C40C43B-3823-4848-8B5A-D2F97A82F79B)

it is not possible to perform or implement wire level access for
Oracle for legal or technical reasons.

**Comment by geoand** [comment]
@vietj what would be the best place to add `PcapWriteHandler` to the pipeline? Asking because when I added it in the same place as the `LoggingHandler`, things did not work becayse `PcapWriteHandler` needs to implement the `channelActive` method.

**Comment by vietj** [comment]
it is not clear what you mean ?

**Comment by geoand** [comment]
I am wondering what the proper place in Vertx is for adding the `PcapWriteHandler` to the Netty processing pipeline is.
If I just add it in the same places where `LoggingHandler` is being setup, then `PcapWriteHandler` results in NPEs because its `channelActive` method has not been called (I presume because it was added too late).

**Comment by vietj** [comment]
that sounds weird, do you have a stack trace ?

**Comment by geoand** [comment]
I'll have to build everything again and capture it. I'll to do that later on today or tomorrow.

**Comment by vietj** [comment]
do you have a branch you can share too ?

**Comment by geoand** [comment]
https://github.com/geoand/vert.x/tree/4.2.2-custom is what I had done. 

But in order to get that working, I needed to also patch Netty and implement `handlerAdded` in `PcapWriteHandler` to simply do what `channelActive` does

**Comment by vietj** [comment]
so the issue is that the handler is added too late and some handlers like logging handler do support it, but not the pcap write handler, is that right ?

**Comment by geoand** [comment]
Exactly, that is how I understood the issue

**Comment by vietj** [comment]
did you try subclassing the handler and have the handlerAdded call the channelActive method as workaround ?

**Comment by geoand** [comment]
I didn't, but I assume that could work.

**Comment by vietj** [comment]
just to see if that works

**Comment by vietj** [comment]
nevertheless it would be good to have this handler in netty lazily handle things

**Comment by geoand** [comment]
Yup, for sure. I'll take another look tomorrow

**Comment by vietj** [comment]
also this handler is final, so it could work with a wrapper I think

**Comment by geoand** [comment]
I have asked on https://github.com/netty/netty/issues/10385 to see if it's safe to implement `handlerAdeed`  as well. I asked because I was seeing some weird behavior which I am not sure is due to me doing something wrong, or `handlerAdded` being incompatible with `PcapWriteHandler`

**Comment by geoand** [comment]
`handlerAdeed` seems to be safe, but I am having problems writing the client and server capture to the same file so I've asked again on the netty issue.

**Comment by vietj** [comment]
can the file path be specified ?

**Comment by vietj** [comment]
I think the file name should be specified when creating the client or the server with something like a pattern in options ?

**Comment by geoand** [comment]
Yes absolutely.

In what I have  now, if the server and client files are different, the capture works properly.

But I really wanted to have the capability to use the same file for all capturing. We'll see if it can happen or not.

**Comment by vietj** [comment]
I think can we use something like a `Function<SocketAddress, AsyncFile>` on `NetClient`, `NetServer` etc... that would be configured with options by default.

**Comment by vietj** [comment]
so default would be to use options, but user can specify a function for ultimate flexibility

**Comment by geoand** [comment]
👍🏼 

I'll wait and see what the Netty folks say about using a single file and then come back to this.

**Comment by geoand** [comment]
I found a few more cycles to take another look at this and actually it seems like the only issue is to properly manage writing the data from multiple sources into the output file.

Now I just need to think of what the proper way of doing that would be

**Comment by geoand** [comment]
https://github.com/eclipse-vertx/vert.x/pull/4260 is a first draft of what I have in mind

**Comment by T-baby** [comment]
I think the http 3 implementation should be prioritized over[ grpc transportability](https://github.com/vert-x3/vertx-grpc/issues/83), that http3 has become the standard now.

**Comment by hakarim740-com-ra** [comment]
QUIC support is a must!

**Comment by raviteja5678** [comment]
@vietj May I know if io.vertx.core.http.HttpServerRequest can be updated in next release to remove the deprecated class javax.security.cert.X509Certificate for Java 17 compatibility ?  
Thanks

**Comment by yeikel** [comment]
> @vietj May I know if io.vertx.core.http.HttpServerRequest can be updated in next release to remove the deprecated class javax.security.cert.X509Certificate for Java 17 compatibility ? Thanks

In what way does this block Java 17 for you?
