### ISSUE TITLE
Vert.x 5 Roadmap

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#610]
### Vert.x 5 Roadmap

[Development of Vert.x 5](https://github.com/eclipse-vertx/vert.x/wiki/Vert.x-5)

### 5.1.0

- [x] Quic
- [x] HTTP/3
- [ ] Jackson
  - [ ] Jackson v3
  - [ ] Use Jackson LTS / configure dependabot accordingly
- [ ] MQTT v5
- [ ] gRPC improvements
  - [x] [gRPC event bus bridge](https://github.com/vert-x3/issues/issues/630)
  - [ ]  Use embedded Netty in vertx-grpc-netty](https://github.com/vert-x3/vertx-grpc/issues/155)
- [ ] [Examples](https://github.com/vert-x3/vertx-examples/pull/483)
- [ ] CI
  - [ ] [Finish migration to Java 25](https://github.com/vert-x3/issues/issues/661)
  - [ ] Vert.x 5 parent new release

### 5.0.0

- [x] [Async result callback removals](https://github.com/vert-x3/issues/issues/611)
- [x] Codegen improvements
  - [x] [Modularization (Maven)](https://github.com/eclipse-vertx/vertx-codegen/issues/358)
  - [x] [Extract api in a vertx-codegen-api project](https://github.com/eclipse-vertx/vertx-codegen/pull/377)
  - [x] Repackage vertx-codegen-processor classes in `io.vertx.codegen.processor` package
- [x] JDK 11 based build: Vert.x 5 should switch to JDK 11 as as minimum version, and builds/CI updated accordingly
  - [x] [Vert.x pom parents allow deploy with JDK 11 for Vert.x 5](https://github.com/vert-x3/issues/issues/645)
- [ ] Legacy Java feature cleanup: a couple of Java features are fading away with recent JDK versions, those should be migrated to replacement in Vert.x 5
  - [x] [Java finalization](https://github.com/vert-x3/issues/issues/623)
  - [ ] Biased locking
    - [ ] `synchronized` usage analysis to find un-necessary usage in particular with respect to biased locking
    - [ ] define biased locking removal strategies for each of the various usage
- [x] CLI cleanup: the Vert.x CLI will be removed from Vert.x 5 and the references to the CLI should be removed in Vert.x 4 as much as possible
  - [x] remove CLI usage in Vert.x examples (Vert.x 4 branch) https://github.com/vert-x3/vertx-examples/pull/450
  - [x] remove vertx-unit's CLI command https://github.com/vert-x3/vertx-unit/pull/77
  - [x] Implement Launcher equivalent with Picocli: [Prototype](https://github.com/tsegismont/vertx-application-launcher)
  - [x] Remove CLI usage in Vert.x Core (examples and code) https://github.com/eclipse-vertx/vert.x/pull/4769
  - [x] new repository in Vert.x 5 https://github.com/eclipse-vertx/vertx-launcher/pull/1
    - move the CLI framework to separate JAR (legacy)
    - integrate implementation with Picocli
  - [x] Udpate vertx-dependencies https://github.com/vert-x3/vertx-dependencies/pull/141
  - [x] vertx-stack CLI cleanup https://github.com/vert-x3/vertx-stack/pull/140
    - command part and deployment to central of the packaged zip
    - add new modules to the stack
  - [x] Vert.x Shell update (use the new JAR) https://github.com/vert-x3/vertx-shell/pull/55
  - [x] Website update https://github.com/vertx-web-site/vertx-web-site.github.io/pull/147
  - [x] Starter update (add vertx-application-launcher to Vert.x 5 projects)
  - [x] Implement redeployment in the Vert.x Maven Plugin
  - [x] Update deprecations and breaking changes doc
  - [x] Update Migration guide https://github.com/tsegismont/vertx-5-migration-guide/commit/78d3e4e82882a3ef43419b4d6b41dd3234b40e41
- [x] [Undocumented system properties analysis and cleanup](https://github.com/eclipse-vertx/vert.x/issues/4963)
- [ ] Core API improvements
  - [x] [CompositeFuture methods should use generic Future<?> type instead of Future raw type](https://github.com/eclipse-vertx/vert.x/pull/4684)
  - [x] [Remove obsolete stream implementations (timer stream, request/connect/ws streams, UDP socket stream)](https://github.com/eclipse-vertx/vert.x/pull/4689) 
  - [x] [Logging API removal, the internal logging API is preserved](https://github.com/eclipse-vertx/vert.x/commit/6f47150fa51e4a5a774df11a2efe24fc3b0f5702)
  - [x] [Replace HTTP client host/port properties by an authority property](https://github.com/eclipse-vertx/vert.x/pull/4778/files)
  - [x] [A few HTTP stream writeXXX API are fluent and instead should return a future signaling the success or failure of the write operation](https://github.com/eclipse-vertx/vert.x/pull/4779)
  - [x] [executeBlocking(Handler<Promise<T>>) ➡ executeBlocking(Callable<T>)](https://github.com/eclipse-vertx/vert.x/pull/4782)
  - [x] [Replace Future eventually function argument by a supplier argument](https://github.com/eclipse-vertx/vert.x/pull/4828)
  - [x] [Connect options / per connection SSL options](https://github.com/eclipse-vertx/vert.x/pull/4857)
  - [x] [ClientWebSocket](https://github.com/eclipse-vertx/vert.x/pull/4825/files)
  - [x] [HttpServerResponse close method removal](https://github.com/eclipse-vertx/vert.x/pull/4806)
  - [x] [Simplified lock API](https://github.com/eclipse-vertx/vert.x/pull/4795) 
  - [x] [Vertx builder](https://github.com/eclipse-vertx/vert.x/pull/4959)
  - [x] [HTTP client builder](https://github.com/eclipse-vertx/vert.x/pull/4872)
  - [x] [Timer task as a Vert.x future](https://github.com/eclipse-vertx/vert.x/pull/4992)
  - [x] [Periodic task duplicates the context](https://github.com/eclipse-vertx/vert.x/issues/4993)
  - [x] [Local context data SPI](https://github.com/eclipse-vertx/vert.x/pull/5048)
  - [x] [Inbound read/message queue](https://github.com/eclipse-vertx/vert.x/pull/5180)
  - [x] [Outbound write/message queue](https://github.com/eclipse-vertx/vert.x/pull/4809)
  - [x] [TCP shutdown including WebSocket/HTTP](https://github.com/eclipse-vertx/.eclipsefdn/pull/12)
  - [x] [Buffer fromJson/toJson](https://github.com/eclipse-vertx/vert.x/pull/5345)
  - [x] ReadStream [collector API](https://github.com/eclipse-vertx/vert.x/pull/5208)
  - [x] [Deployment API](https://github.com/eclipse-vertx/vert.x/pull/5318)
  - [x] [Future expectations](https://github.com/eclipse-vertx/vert.x/pull/5118)
  - [x] [HTTP response expectations](https://github.com/eclipse-vertx/vert.x/pull/5118)
  - [x] [HTTP client connection](https://github.com/eclipse-vertx/vert.x/pull/5070)
  - [x] [HTTP stream reset should be asynchronous](https://github.com/eclipse-vertx/vert.x/pull/5412)
  - [x] [Rename WebsocketVersion to WebSocketVersion](https://github.com/eclipse-vertx/vert.x/pull/5374)
  - [x] [Integrate io_uring as a transport](https://github.com/eclipse-vertx/vert.x/pull/5320)
  - `void start(Handler<Future<Void>>)` ➡ `Future<T> start()`
  - `WriteStream#write(...)` returns a result extending `Future` allowing the result to signal back-pressure
    - avoids the write then `writeQueueFull` potentially racy (non event-loop) pattern
  - `Future<T>` should not extend anymore `AsyncResult<T>`
  - Remove `SelfSignedCertificate` that does not work after Java 8 du to JDK changes
  - Harmonize getter/setter naming convention across the API
  - Consider removing `NoStackTraceThrowable` https://github.com/eclipse-vertx/vert.x/issues/5012
- [ ] More data object conversion
  - [x] [vertx-core](https://github.com/eclipse-vertx/vert.x/pull/5354)
- [x] gRPC improvements
  - [x] [JSON wire format](https://github.com/eclipse-vertx/vertx-grpc/pull/108) 
  - [x] [gRPC Web](https://github.com/eclipse-vertx/vertx-grpc/issues/55)
  - [x] [Timeout and deadline](https://github.com/eclipse-vertx/vertx-grpc/pull/78)
- [x] Service proxies improvements
  - [x] [data object protobuf support](https://github.com/eclipse-vertx/vertx-codegen/pull/356)
  - [x] [protofile generation](https://github.com/eclipse-vertx/vertx-codegen/pull/356)
- [ ] Usability improvements
  - [ ] [Shared client configuration](https://github.com/vert-x3/issues/issues/626)
  - [ ] Builders 
    - [x] [Builder style API guidelines](https://github.com/eclipse-vertx/vert.x/wiki/Builder-pattern-guidelines)
    - [x] [Vertx builder](https://github.com/eclipse-vertx/vert.x/pull/4962)
    - [x] [HTTP client builder](https://github.com/eclipse-vertx/vert.x/pull/4872)
    - [x] [SQL client builder](https://github.com/eclipse-vertx/vertx-sql-client/pull/1357) 
    - [x] [Builders for GraphQL handlers](https://github.com/vert-x3/vertx-web/issues/2518)
  - [x] [Transform GraphiQL setup into subrouter creation](https://github.com/vert-x3/vertx-web/issues/2517)
- [ ] [RabbitMQ client](https://github.com/vert-x3/issues/issues/628)
- [x] SQL client improvements
  - [x] remove Pool sub interfaces
  - [x] remove map of `NetClient`
  - [x] SqlConnectOptions should not extend anymore NetClientOptions
  - [x] remove `Pool#connectionProvider` that is replaced by `Supplier<Future<SqlConnectOptions>>`
  - [x] [JDBC implementation use SQL common connection pool](https://github.com/vert-x3/vertx-jdbc-client/pull/313)
  - [x] [removal of deprecated legacy SQL client API](https://github.com/vert-x3/vertx-jdbc-client/pull/313)
- [x] Micrometer
  - [x] [Micrometer improvements](https://github.com/vert-x3/vertx-micrometer-metrics/issues/184)
  - [x] [Enable pool name tag by default](https://github.com/vert-x3/vertx-micrometer-metrics/issues/231)
- [x] Service Discovery and load balancing for Vert.x clients
  - [x] [Address resolver SPI](https://github.com/eclipse-vertx/vert.x/pull/4676)
  - [x] Service discovery and load balancing integrating with address resolver SPI
  - [x] More load balancing policies https://github.com/eclipse-vertx/vert.x/issues/5154
    - [x] Random
    - [x] Power of two choices
    - [x] Hash based load-balancing (incl. sticky session) https://github.com/eclipse-vertx/vert.x/issues/5165
  - [x] [Generic service lookup](https://github.com/eclipse-vertx/vertx-service-resolver/pull/9)
- [x] [Health checks dependencies cleanup](https://github.com/vert-x3/issues/issues/632)
- [x] [Circuit breaker improvements](https://github.com/vert-x3/issues/issues/633)
- [x] [Json Schema deprecated classes cleanup](https://github.com/eclipse-vertx/vertx-json-schema/issues/114)
  - [x] [Update vertx-web](https://github.com/vert-x3/vertx-web/pull/2455)
- [ ] [Release process](https://github.com/vert-x3/issues/issues/620)
- [x] [Netty 4 decoupling](https://github.com/vert-x3/issues/issues/641)
  - [x] [Remove Netty from API usage](https://github.com/eclipse-vertx/vert.x/pull/4791)
- [x] [Infinispan 14 update](https://github.com/vert-x3/vertx-infinispan/issues/129)
- [x] [Hazelcast 5 update](https://github.com/vert-x3/vertx-hazelcast/issues/185)
- [x] [Support request forwarding to Web API Service in OpenAPI Router](https://github.com/vert-x3/vertx-web/issues/2478)
- [x] Context
  - [x] [Resource segregation](https://github.com/eclipse-vertx/vert.x/pull/5259)
  - [x] [Event executor SPI](https://github.com/eclipse-vertx/vert.x/pull/5280)
- [x] JPMS support
  - [x] codegen split package removal
    - [x] [vertx-codegen split package removal](https://github.com/eclipse-vertx/vertx-codegen/pull/382)
    - [x] [vertx-service-proxy](https://github.com/vert-x3/vertx-service-proxy/pull/150/files) 
    - [x] [vertx-sql-client](https://github.com/eclipse-vertx/vertx-sql-client/pull/1443) 
    - [x] [vertx-rx](https://github.com/vert-x3/vertx-rx/pull/310)
    - [x] [vertx-lang-kotlin](https://github.com/vert-x3/vertx-lang-kotlin/pull/265) 
  - [x] [vertx-auth split package removal](https://github.com/eclipse-vertx/vertx-auth/pull/679)
  - [x] [Netty JPMS support](https://github.com/netty/netty/issues/14176)
  - [x] [vertx-codegen JPMS support](https://github.com/eclipse-vertx/vertx-codegen/pull/386)
  - [x] [vertx-core JPMS preparation alternative 1](https://github.com/eclipse-vertx/vert.x/pull/5232)
  - [x] [vertx-core JPMS preparation alternative 2](https://github.com/eclipse-vertx/vert.x/pull/5233)
  - [x] [vertx-core JPMS support](https://github.com/eclipse-vertx/vert.x/pull/5244)
  - [x] [vertx-sql-client JPMS support](https://github.com/eclipse-vertx/vertx-sql-client/pull/1445)
  - [x] [vertx-jdbc-client JPMS support](https://github.com/vert-x3/vertx-jdbc-client/pull/316)
  - [x] [vertx-auth JPMS support](https://github.com/eclipse-vertx/vertx-auth/pull/682)
  - [x] [vertx-uri-template JPMS support](https://github.com/eclipse-vertx/vertx-uri-template/pull/8)
  - [x] [vertx-json-schema JPMS support](https://github.com/eclipse-vertx/vertx-json-schema/pull/138)
  - [x] [vertx-openapi JPMS support](https://github.com/eclipse-vertx/vertx-openapi/pull/76)
  - [x] [vertx-service-resolver JPMS support](https://github.com/eclipse-vertx/vertx-service-resolver/pull/12)
  - [x] [vertx-grpc JPMS support](https://github.com/eclipse-vertx/vertx-grpc/pull/103)
  - [x] [vertx-http-proxy JPMS support](https://github.com/eclipse-vertx/vertx-http-proxy/pull/87)
  - [x] [vertx-grpc io.grpc decoupling](https://github.com/eclipse-vertx/vertx-grpc/pull/104)
  - [x] [vertx-redis-client JPMS support](https://github.com/vert-x3/vertx-redis-client/pull/472)
  - [x] [vertx-mail-client JPMS support](https://github.com/vert-x3/vertx-mail-client/commit/1dfd954f05dc67e385e59c03ad7d344327574b12)
  - [x] [vertx-cassandra-client JPMS support](https://github.com/vert-x3/vertx-cassandra-client/pull/87)
  - [x] [vertx-mongo-client JPMS support](https://github.com/vert-x3/vertx-mongo-client/pull/318)
  - [x] [vertx-bridge-common](https://github.com/vert-x3/vertx-bridge-common/pull/10) 
  - [x] vertx-web
    - [x] [common + client](https://github.com/vert-x3/vertx-web/pull/2650)
    - [x] [other components](https://github.com/vert-x3/vertx-web/pull/2654)
  - [x] vertx metrics
    - [x] [vertx-dropwizard-metrics](https://github.com/vert-x3/vertx-dropwizard-metrics/actions/runs/10990215712)
    - [x] vertx-micrometer-metrics
  - [x] [vertx-tracing](https://github.com/eclipse-vertx/vertx-tracing/pull/82)
  - [ ] vertx-clustering
    - [x] [vertx-hazelcast](https://github.com/vert-x3/vertx-hazelcast/pull/202)
    - [ ] others
  - [x] vertx-unit/junit
  - [x] vertx-jdbc-client
  - [x] vertx-mqtt
  - [x] vertx-stomp
  - [x] [vertx-service-proxy](https://github.com/vert-x3/vertx-service-proxy/actions/runs/11114384055) 
  - [x] [vertx-proton](https://github.com/vert-x3/vertx-proton/pull/136)
  - [x] [vertx-amqp-client](https://github.com/vert-x3/vertx-amqp-client/pull/85)
  - [x] [vertx-consul-client](https://github.com/vert-x3/vertx-consul-client/pull/110)
  - [x] [vertx-health-checks](https://github.com/vert-x3/vertx-health-check/pull/60)
  - [x] [vertx-config](https://github.com/vert-x3/vertx-config/pull/164)
  - [x] [vertx-circuit-breaker](https://github.com/vert-x3/vertx-circuit-breaker/pull/75) 
  - [ ] [cleanup / review assigned module names](https://github.com/vert-x3/issues/issues/648)
- [x] Vert.x Tracing
  - [x] [Use names specified by OpenTelemetry for tags](https://github.com/eclipse-vertx/vertx-tracing/issues/69)
- [ ] Vertx Metrics
  - [ ] client metrics consistency and documentation
    - [x] redis
    - [x] sql client
    - [ ] ...
  - [x] metrics implementation should avoid specify a registry (micrometer) and instead it should be set on the vertx builder with a specific VertxMetricsFactory, deprecations in Vert.x 4.x should be applied
- [ ] Review Vert.x 5 [backlog](https://github.com/issues?q=is%3Aopen+org%3Avert-x3+org%3Aeclipse-vertx+milestone%3A5.0.0)
- [ ] Release prep
  - [x] Ensure we use VerticleBase everywhere
  - [x] [Example improvements](https://github.com/vert-x3/vertx-examples/issues/460)
  - [x] Migration guide
  - [x] Modular guide
  - [ ] Investigate GitHub dev container for how-to / example
  - [ ] Improve generation of release notes / breaking change
  - [x] Blog post

### 5.x

- [ ] SQL client
  - [ ] possibly improve `Query` collector/mapping that are not composable
  - [ ] [stored procedure API](https://github.com/eclipse-vertx/vertx-sql-client/issues/1246)
  - [ ] [HA support for PostgreSQL or more](https://github.com/eclipse-vertx/vertx-sql-client/issues/1250)
- [ ] CouchDB client
- [ ] [Non racy HTTP client methods when called outside event-loop](https://github.com/eclipse-vertx/vert.x/pull/4705)
- [ ] Extra service resolver registry integration
- [ ] Core API improvements
  - [ ] Vertx shutdown / restart
- [ ] Service proxies improvements
  - [ ] [service proxy using protobuf transport](https://github.com/vert-x3/vertx-service-proxy/issues/147)
  - [ ] service proxy streaming
    - [ ] #643

### Components deprecation

- [ ] Service Discovery
- [ ] Vert.x gRPC Netty

### Components sunset

- [x] [RxJava 1](https://github.com/vert-x3/vertx-rx/pull/322/files)
- [x] [WebAuthn](https://github.com/eclipse-vertx/vertx-auth/pull/706)
- [x] [Sync](https://github.com/vert-x3/vertx-sync/issues/47)
- [x] [Maven Service Factory](https://github.com/vert-x3/vertx-maven-service-factory/issues/39)
- [x] [HTTP Service Factory](https://github.com/vert-x3/vertx-http-service-factory/issues/16)
- [x] [Service Factory](https://github.com/vert-x3/vertx-service-factory/issues/16)
- [x] [Docker base image generation](https://github.com/vert-x3/vertx-stack/issues/137)

**Comment by hakarim740-com-ra** [comment]
Can we have support for HTTP/3?

**Comment by vietj** [comment]
it shall be implemented but most likely in 5.x, x > 0

**Comment by hakarim740-com-ra** [comment]
> it shall be implemented but most likely in 5.x, x > 0

Can we get `vertx.createQuicServer()` or `QuicServer.create(vertx)` too?
