### ISSUE TITLE
Stack wide async result callback removals

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#611]
Vert.x 5 does not expose callbacks API anymore.

This impacts the entire stacks, it can be split in two steps 

## Step 1: async result callback usage cleanup

Unfortunately, Vertx implementation often relies on callback methods and therefore we must start to replace such use by their future method counterparts.

The following strategy can be used to address this while minimising errors

- [x] [Update](https://github.com/eclipse-vertx/vertx-codegen/pull/352) codegen to fail the java compilation when a callback method is not deprecated, this relies on the Java compiler and therefore provides precise error reporting which can be used to quickly annotate all callback methods
- [x] [Update](https://github.com/vert-x3/issues/issues/612) the Vert.x codebase to deprecate all callbacks 
- [x] [Update](https://github.com/vert-x3/issues/issues/616) the Vert.x codebase (implementation and tests) to cleanup callback usage relying on Java compiler linting or build tools (IntelliJ) that can find deprecated method usage
- [x] [Update](https://github.com/eclipse-vertx/vert.x/actions/runs/4425347749) `WriteStream` to remove callback methods, update the stack implementations
- [x] Update cluster manager implementations to not implement the cluster manager callback API

## Step 2: async result callback api cleanup

In this step, we remove callback methods from the API. A few Vert.x existing modules that were created in Vert.x 4 already use this feature (Vert.x gRPC, Vert.x HTTP Proxy, etc...).

We simply can switch Vert.x modules to use only futures, granted that we removed the callback method use in the previous steps. As precaution we should proceed from the leaf to the root of the dependency tree (vertx-core being the root of the tree).

- [x] [Update](https://github.com/vert-x3/issues/issues/619) each module to exclusively use futures

## Step 3: cleanup callback support in code generators

In this step, we finalise with the removal of the code generators that supported callbacks

- [x] vertx-service-proxies
- [x] vertx-lang-kotlin
- [x] vertx-rx
- [x] vertx-codegen
